FROM node:16

WORKDIR .

COPY package*.json ./
COPY tsconfig*.json ./
COPY .eslintrc.js ./
COPY .env ./

RUN npm install
RUN npm install prisma --save-dev
COPY apps/bikes ./
COPY prisma/schema.prisma .
RUN npx prisma generate

EXPOSE 5671

CMD ["npm", "run", "start:dev"]
